// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSemlgTrScWfBf7lj1XMfReVS6OQ_qOo',
    appId: '1:832916460703:web:c4326f0fa0caaec1dabeaa',
    messagingSenderId: '832916460703',
    projectId: 'whatsapp-clone-a4792',
    authDomain: 'whatsapp-clone-a4792.firebaseapp.com',
    storageBucket: 'whatsapp-clone-a4792.appspot.com',
    measurementId: 'G-TSJVVQSGEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRnoWCGNuH9Aesv5NPf3M9E9OQ68WhH4',
    appId: '1:832916460703:android:750c00027e5c2fe0dabeaa',
    messagingSenderId: '832916460703',
    projectId: 'whatsapp-clone-a4792',
    storageBucket: 'whatsapp-clone-a4792.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdSemlgTrScWfBf7lj1XMfReVS6OQ_qOo',
    appId: '1:832916460703:web:bdba023e0970dc48dabeaa',
    messagingSenderId: '832916460703',
    projectId: 'whatsapp-clone-a4792',
    authDomain: 'whatsapp-clone-a4792.firebaseapp.com',
    storageBucket: 'whatsapp-clone-a4792.appspot.com',
    measurementId: 'G-86R3V89M36',
  );

}